Always show commit headers with stg show
When using `stg show --stat`, the commit headers were not being shown. This
behavior was inconsistent with `git show` which always shows the commit
headers, even with `git show --stat`.

This repair is affected by outputting the `git show --stat` directly
instead of piping the diffs through lib.git.diffstat() which uses `git
apply --stat`.

This has the side-effect of repairing `stg show --stat` for empty patches.
Running `stg show --stat` on an empty patch (patch without a diff) used to
cause the following error:

    error: unrecognized input
    stg show: git failed with code 128

Test cases are added to check all of the above.

Signed-off-by: Peter Grayson <pete@jpgrayson.net>